name: Update README with Recent Activity

on:
  schedule:
    - cron: '* * * * *' # Runs every minute (TESTING)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README with Recent Activity

    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Updated README with recent activity'
          MAX_LINES: 10
