name: Update README with Recent Activity

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours (backup)

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README with Recent Activity

    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Updated README with recent activity'
          MAX_LINES: 10
